# scripts/build_exercise_bank.py — ONE-TIME generator for src/exerciseBank.js.
# Source of truth: the archived PT xlsx (2026-07-13). Re-run only if Elie ships
# a new bank; then bump EXERCISE_BANK_VERSION below and re-review the output.
# Run: python scripts/build_exercise_bank.py   (from repo root; needs openpyxl)
import openpyxl, re, json, io

SRC = r"C:\projects\_archive\PTApp\program-source\2026-07-13-exercises-full-list.xlsx"
OUT = "src/exerciseBank.js"
BANK_VERSION = 1

# Typos / variants observed in the xlsx -> canonical muscle names
CANON = {
    "hmastrings": "Hamstrings", "spinal erectors": "Spinal Erectors",
    "forearms flexors": "Forearms", "forearms extensors": "Forearms",
    "rear delt": "Rear Delts", "serratus anterior": "Serratus",
    "upper back": "Upper Back", "middle back": "Middle Back",
}
def canon(m):
    m = m.strip().strip('"').strip()
    return CANON.get(m.lower(), " ".join(w.capitalize() for w in m.split()))

# canonical muscle -> (slot, bucket). bucket is the QUOTA key: the major name
# ('Chest'/'Back'/'Legs') or the minor name from spec §6's table. None = prehab,
# excluded from auto-programming (Rotator Cuffs, Psoas, Serratus).
BUCKET = {
    "Chest": ("push", "Chest"),
    "Lats": ("pull", "Back"), "Middle Back": ("pull", "Back"), "Upper Back": ("pull", "Back"),
    "Back": ("pull", "Back"), "Traps": ("pull", "Back"), "Spinal Erectors": ("pull", "Back"),
    "Quads": ("legs", "Legs"), "Hamstrings": ("legs", "Legs"), "Glutes": ("legs", "Legs"),
    "Adductors": ("legs", "Legs"), "Abductors": ("legs", "Legs"),
    "Shoulders": ("push", "Shoulders"), "Triceps": ("push", "Triceps"),
    "Rear Delts": ("pull", "Rear Delts"), "Biceps": ("pull", "Biceps"), "Forearms": ("pull", "Forearms"),
    "Calves": ("legs", "Calves"), "Abs": ("legs", "Abs"), "Obliques": ("legs", "Abs"),
    "Rotator Cuffs": (None, None), "Psoas": (None, None), "Serratus": (None, None),
}

# Compound if name matches these movement patterns, unless explicitly isolated.
COMPOUND_PAT = re.compile(
    r"squat|deadlift|press|lunge|row(?!ing)|pull-up|pull up|chin-up|dip\b|thrust"
    r"|push-up|push up|step-up|rack pull|good morning|clean", re.I)
ISOLATION_OVERRIDE = {  # matches pattern but is single-joint in practice
    "Pallof Press", "Anti Rotation", "Landmine Rainbow", "Leg Press Wide Stance",
}
COMPOUND_OVERRIDE = {"Glute Ham Raise", "Back Extension", "Nordic Hamstring Curl"}

# High-skill barbell lifts filtered out for begA/begB when alternatives exist
# (anchors are exempt in the kernel, not here).
ADVANCED = re.compile(r"barbell|deficit|halting|power rack|push press|nordic|pistol|plyometric", re.I)

wb = openpyxl.load_workbook(SRC, data_only=True)
ws = wb.worksheets[0]
seen, out = set(), []
for name_cell, muscles_cell in ws.iter_rows(min_row=2, values_only=True):
    if not name_cell or not muscles_cell: continue
    name = re.sub(r"\s+", " ", str(name_cell)).strip()
    if name.lower() in seen: continue          # dedupe (keep FIRST occurrence)
    seen.add(name.lower())
    # muscle cell is JSON-ish with broken quotes in places -> extract words
    muscles = [canon(m) for m in re.findall(r'[A-Za-z][A-Za-z ]*[A-Za-z]', str(muscles_cell))]
    muscles = list(dict.fromkeys(muscles))     # unique, order-preserving
    unknown = [m for m in muscles if m not in BUCKET]
    if unknown: raise SystemExit(f"UNKNOWN MUSCLE {unknown} in '{name}' — extend CANON/BUCKET")
    primary = muscles[0]
    slot, bucket = BUCKET[primary]
    is_comp = (name in COMPOUND_OVERRIDE) or (
        bool(COMPOUND_PAT.search(name)) and not any(o.lower() in name.lower() for o in ISOLATION_OVERRIDE))
    out.append({"name": name, "muscles": muscles, "primary": primary,
                "type": "compound" if is_comp else "isolation",
                "slot": slot, "bucket": bucket,
                "advanced": bool(ADVANCED.search(name))})

buf = io.StringIO()
buf.write("// GENERATED by scripts/build_exercise_bank.py — DO NOT EDIT BY HAND.\n")
buf.write("// Source: _archive/PTApp/program-source/2026-07-13-exercises-full-list.xlsx (Elie's bank).\n")
buf.write("// Regenerate + bump version only when Elie ships a new bank.\n")
buf.write(f"export const EXERCISE_BANK_VERSION = {BANK_VERSION};\n\n")
buf.write("export const MUSCLE_GROUPS = {\n")
buf.write("  push: { major: 'Chest', minors: ['Shoulders', 'Triceps'] },\n")
buf.write("  pull: { major: 'Back', minors: ['Rear Delts', 'Biceps', 'Forearms'] },\n")
buf.write("  legs: { major: 'Legs', minors: ['Calves', 'Abs'] },\n};\n\n")
buf.write("export const EXERCISES = " + json.dumps(out, indent=2) + ";\n\n")
buf.write("""// All exercises whose primary muscle rolls up into `bucket` (major or minor name).
export const bankForBucket = (bucket) => EXERCISES.filter(e => e.bucket === bucket);
""")
with open(OUT, "w", encoding="utf-8") as f: f.write(buf.getvalue())
print(f"wrote {OUT}: {len(out)} exercises")
