#!/usr/bin/env node
// build_fonts — regenerate src/fonts.css from Google Fonts, inlined as base64.
//
// WHY A SCRIPT AND NOT A <link>. The app is a single-file build that ships
// inside a native shell and runs offline; a stylesheet link to a font CDN is a
// blank first paint on a bad connection and a third-party request in a store
// listing. So the faces are downloaded ONCE, at build-authoring time, and live
// in the repo as data URIs. src/fonts.css is generated — do not hand-edit it.
//
// 🔴 LATIN SUBSETS ONLY. Saira has no Arabic coverage, so the Arabic build
//    falls back to the platform Arabic face and carries hierarchy through
//    weight rather than uppercase (Arabic has no case, and letter-spacing
//    breaks its joins). Adding IBM Plex Sans Arabic here is a follow-on.
//
// Run: node scripts/build_fonts.mjs   (needs network; ~165 KB of woff2)

import { writeFileSync } from 'node:fs';

const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=Saira+Condensed:wght@600;700'
  + '&family=Saira:wght@400;500;600'
  + '&family=IBM+Plex+Mono:wght@500;600'
  + '&display=swap';

// Google serves woff2 only to a browser-looking UA; without this it returns the
// legacy truetype build, which is roughly four times the size.
const UA = 'Mozilla/5.0 (Windows NT 10.0; rv:120.0) Gecko/20100101 Firefox/120.0';

const HEADER = `/* ─── Bundled type (v2.18, design pass stage 2) ───────────────────────────────
   🔴 GENERATED BY scripts/build_fonts.mjs — DO NOT HAND-EDIT.
   Latin subsets of Saira Condensed (display), Saira (body) and IBM Plex Mono
   (all digits), inlined as base64 so the app never fetches a font at runtime.
   Roles and the Arabic rule: spec §4 and the script's own header. */
`;

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

// Google emits one /* subset */ comment before each @font-face block.
const parts = css.split(/\/\*\s*([a-z0-9-]+)\s*\*\//i).slice(1);
let out = HEADER;
let raw = 0;
for (let i = 0; i < parts.length; i += 2) {
  if (parts[i] !== 'latin') continue;              // latin-ext, cyrillic, greek: not shipped
  const block = parts[i + 1];
  const family = block.match(/font-family: '([^']+)'/)[1];
  const weight = block.match(/font-weight: (\d+)/)[1];
  const url = block.match(/url\((https:[^)]+)\)/)[1];
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  raw += buf.length;
  // font-display: block is safe ONLY because the bytes are already in the
  // document — there is no network round trip that could leave text invisible.
  out += `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};`
    + `font-display:block;src:url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2');}\n`;
}

writeFileSync(new URL('../src/fonts.css', import.meta.url), out);
console.log(`✓ src/fonts.css — ${raw} bytes of woff2, ${out.length} bytes of CSS`);
