// Arabic display names for the exercise bank (v2.14.2) — HANDWRITTEN, not generated.
// Keyed by the EXACT English `name` in exerciseBank.js — the same string frozen
// into program records, so old programs get Arabic automatically at display time.
// Drafted by Claude 2026-07-17 (standard Lebanese-gym terminology, loanwords
// kept where they ARE the gym vocabulary: بنش برس، سكوات، ديدلفت، كيرل…);
// Elie corrects phrasing in follow-up one-line edits — the viewer shows the
// English original in small text exactly so he can spot entries to fix.
// Coverage enforced by scripts/sanity/sanity-exercise-names-ar.mjs (all 340,
// no stray keys, Arabic script in every value). A NEW bank version may ship
// before its translations: unknown names fall back to English in the viewer.
export const EXERCISE_NAMES_AR = {
  'Hammer Curl': 'هامر كيرل',
  'Shoulder External Rotation with Cable': 'تدوير خارجي للكتف بالكيبل',
  'Seated Dumbbell Curl': 'كيرل بالدمبل جالسًا',
  'Dumbbell W Raise': 'رفعة W بالدمبل',
  'High Pulley Curl': 'كيرل بالبكرة العالية',
  'Barbell Curl': 'كيرل بالبار',
  'Machine Curl': 'كيرل بالجهاز',
  'Preacher Curl': 'بريتشر كيرل',
  'Reverse-Grip Barbell Curl': 'كيرل بالبار بقبضة عكسية',
  'Barbell Reverse Wrist Curl': 'ثني الرسغ العكسي بالبار',
  'Barbell Wrist Curl': 'ثني الرسغ بالبار',
  'Triceps Pushdown': 'بوشداون ترايسبس',
  'Reverse-Grip Cable Pushdown': 'بوشداون بقبضة عكسية',
  'One Arm Reverse-Grip Pushdown': 'بوشداون بذراع واحدة بقبضة عكسية',
  'Barbell Lying Triceps Extension': 'مد ترايسبس بالبار مستلقيًا',
  'Dumbbell Lying Triceps Extension': 'مد ترايسبس بالدمبل مستلقيًا',
  'One Arm Overhead Dumbbell Triceps Extension': 'مد ترايسبس فوق الرأس بذراع واحدة',
  'Seated Overhead Dumbbell Triceps Extension': 'مد ترايسبس فوق الرأس بالدمبل جالسًا',
  'Triceps Kickback': 'ركلة ترايسبس خلفية',
  'Triceps Dip': 'متوازي ترايسبس',
  'Lying Shoulder External Rotation with Dumbbell': 'تدوير خارجي للكتف بالدمبل مستلقيًا',
  'Dumbbell Batwing': 'جناح الخفاش بالدمبل',
  'Barbell Behind the Neck Press': 'برس خلف الرقبة بالبار',
  'Seated Barbell Overhead Press': 'برس كتف بالبار جالسًا',
  'Seated Dumbbell Overhead Press': 'برس كتف بالدمبل جالسًا',
  'Arnold Dumbbell Press': 'أرنولد برس',
  'Bent-Over Lateral Raise': 'رفرفة جانبية بالانحناء',
  'Lateral Dumbbell Raise': 'رفرفة جانبية بالدمبل',
  'Front Dumbell Raise': 'رفرفة أمامية بالدمبل',
  'Side-Lying Lateral Raise': 'رفرفة جانبية مستلقيًا على الجنب',
  'Low-Pulley Lateral Raise': 'رفرفة جانبية بالبكرة المنخفضة',
  'Low-Pulley Front Raise': 'رفرفة أمامية بالبكرة المنخفضة',
  'High-Pulley Lateral Extension': 'مد جانبي بالبكرة العالية',
  'Low-Pulley Bent-Over Lateral Raise': 'رفرفة خلفية بالبكرة المنخفضة',
  'Barbell Front Raise': 'رفرفة أمامية بالبار',
  'Upright Row': 'تجديف عمودي',
  'Pec-Deck Rear Delt Raise': 'رفرفة خلفية على جهاز الفراشة',
  'Incline Barbell Press': 'بنش برس مائل بالبار',
  'Flat Barbell Press': 'بنش برس مستوٍ بالبار',
  'Close Grip Bench Press': 'بنش برس بقبضة ضيقة',
  'Wide Grip Bench Press': 'بنش برس بقبضة واسعة',
  'Decline Barbell Press': 'بنش برس منحدر بالبار',
  'Push-Up': 'تمرين الضغط',
  'Dip': 'متوازي',
  'Flat Dumbbell Press': 'بنش برس مستوٍ بالدمبل',
  'Flat Dumbbell Fly': 'فراشة بالدمبل على مقعد مستوٍ',
  'Incline Dumbbell Fly': 'فراشة بالدمبل على مقعد مائل',
  'Pec-Deck Fly': 'فراشة على الجهاز',
  'Cable Crossover Fly': 'تقاطع كيبل (كروس أوفر)',
  'Dumbbell Pullover': 'بول أوفر بالدمبل',
  'Reverse Chin-Up': 'عقلة بقبضة عكسية',
  'Pull-Up': 'عقلة',
  'Wide Grip Lat Pull-Down': 'سحب علوي بقبضة واسعة',
  'Close Grip Lat Pull-Down': 'سحب علوي بقبضة ضيقة',
  'Straight Arm Lat Pull-Down': 'سحب علوي بذراعين مستقيمتين',
  'Seated Cable Row': 'تجديف بالكيبل جالسًا',
  'One Arm Dumbbell Row': 'تجديف بالدمبل بذراع واحدة',
  'Barbell Bent-Over Row': 'تجديف بالبار بالانحناء',
  'T-bar row': 'تجديف تي-بار',
  'Cable Bent Over Row': 'تجديف بالكيبل بالانحناء',
  'Deadlift': 'ديدلفت',
  'Back Extension': 'مد الظهر',
  'Machine Torso Extension': 'مد الظهر بالجهاز',
  'Barbell Shrug': 'هز الكتفين بالبار',
  'Dumbbell Shrug': 'هز الكتفين بالدمبل',
  'Dumbbell Squat': 'سكوات بالدمبل',
  'Front Squat': 'سكوات أمامي',
  'Back Squat': 'سكوات خلفي',
  'Leg Press': 'ليج برس',
  'Hack Squat': 'هاك سكوات',
  'Barbell Split Squat': 'سبليت سكوات بالبار',
  'Plyometric Squat': 'سكوات قفز (بلايومترك)',
  'Ball Squat': 'سكوات بالكرة',
  'Bodyweight Squat': 'سكوات بوزن الجسم',
  'Sumo Squat': 'سكوات سومو',
  'Smith Machine Squat': 'سكوات على جهاز سميث',
  'Leg Extension': 'مد الرجلين بالجهاز',
  'Lying Leg Curl': 'ثني الرجلين مستلقيًا',
  'Standing Leg Curl': 'ثني الرجلين واقفًا',
  'Seated Leg Curl': 'ثني الرجلين جالسًا',
  'Good Morning': 'جود مورنينغ',
  'Bulgarian Split Squat': 'سكوات بلغاري',
  'Dumbbell Lunge': 'لانج بالدمبل',
  'Barbell Lunge': 'لانج بالبار',
  'Walking Lunge': 'لانج مشي',
  'Plyometric Lunge': 'لانج قفز (بلايومترك)',
  'Stiff-Legged Deadlift': 'ديدلفت بأرجل مشدودة',
  'Sumo Deadlift': 'ديدلفت سومو',
  'Cable Adduction': 'ضم الفخذ بالكيبل',
  'Adduction Machine': 'جهاز ضم الفخذين',
  'Abduction Machine': 'جهاز إبعاد الفخذين',
  'Standing Calf Raise': 'رفع السمانة واقفًا',
  'Dumbbell Standing Calf Raise': 'رفع السمانة بالدمبل واقفًا',
  'One Leg Toe Raise': 'رفع السمانة برجل واحدة',
  'Donkey Calf Raise': 'رفع السمانة بوضعية الانحناء (دونكي)',
  'Seated Calf Raise': 'رفع السمانة جالسًا',
  'Bodyweight Back Kick': 'ركلة خلفية بوزن الجسم',
  'Machine Hip Extension': 'مد الورك بالجهاز',
  'Cable Back Kick': 'ركلة خلفية بالكيبل',
  'Floor Valslide Leg Curl': 'ثني الرجلين بالأقراص المنزلقة أرضًا',
  'Cable Hip Abduction': 'إبعاد الورك بالكيبل',
  'Standing Machine Hip Abduction': 'إبعاد الورك بالجهاز واقفًا',
  'Floor Hip Abduction': 'إبعاد الورك أرضًا',
  'Nordic Hamstring Curl': 'ثني نورديك للخلفية',
  'Floor Sit-up': 'سيت أب أرضًا',
  'Incline Bench Sit-up': 'سيت أب على مقعد مائل',
  'High-Pulley Crunch': 'كرنش بالبكرة العالية',
  'Ab Crunch Machine': 'كرنش بالجهاز',
  'Leg Raise': 'رفع الرجلين',
  'Hanging Leg Raise': 'رفع الرجلين معلقًا',
  'Broomstick Twist': 'التواء بالعصا',
  'Dumbbell Side Bend': 'إمالة جانبية بالدمبل',
  'Obliques Roman Chair Side Bend': 'إمالة جانبية على الكرسي الروماني',
  'Machine Trunk Rotation': 'تدوير الجذع بالجهاز',
  'Russian Twist': 'التواء روسي',
  'Chest Press Machine': 'جهاز ضغط الصدر',
  'Chest Stretch': 'إطالة الصدر',
  'Cable Biceps Curl': 'كيرل بايسبس بالكيبل',
  'Dumbbell Row': 'تجديف بالدمبل',
  'Oblique Crunch': 'كرنش جانبي',
  'Dumbbell Deadlift': 'ديدلفت بالدمبل',
  'Dumbbell Romanian Deadlift': 'ديدلفت روماني بالدمبل',
  'Dumbbell Sumo Squat': 'سكوات سومو بالدمبل',
  'Dumbbell Bridge': 'جسر بالدمبل',
  'Single Leg Squat': 'سكوات برجل واحدة',
  'One Arm Dumbbell Front Raise': 'رفرفة أمامية بذراع واحدة',
  'One Arm Dumbbell Lateral Raise': 'رفرفة جانبية بذراع واحدة',
  'Leg Press Wide Stance': 'ليج برس بوقفة واسعة',
  'Barbell Hip Thruster': 'هيب ثراست بالبار',
  'Crunches': 'كرنش',
  'TRX Chest': 'ضغط صدر TRX',
  'Halting Deadlift': 'ديدلفت متوقف',
  'Rack Pull': 'راك بول',
  'Power Shrug': 'باور شراغ',
  'Deficit Deadlift': 'ديدلفت من مستوى منخفض',
  'Glute Ham Raise': 'جلوت هام ريز',
  'Reverse Hyperextension': 'مد الظهر العكسي',
  'Box Squat': 'سكوات على الصندوق',
  'Power Rack Partial Squat': 'سكوات جزئي على الرف',
  'Power Rack Partial Bench Press': 'بنش برس جزئي على الرف',
  'Push Press': 'بوش برس',
  'Power Rack Partial Shoulder Press': 'برس كتف جزئي على الرف',
  'Prone Plank': 'بلانك على الساعدين',
  'Straight Arm Plank': 'بلانك بذراعين مستقيمتين',
  'Prone Plank on Stability Ball (Arms or Feet Elevated)': 'بلانك على كرة التوازن (ذراعان أو قدمان مرفوعتان)',
  'Straight Arm Plank on Stability Ball(Arms or Feet Elevated)': 'بلانك بذراعين مستقيمتين على كرة التوازن',
  'Bent Knees Leg Lower': 'إنزال الرجلين بركبتين مثنيتين',
  'Extended Knees Leg Lower': 'إنزال الرجلين بركبتين ممدودتين',
  'Leg Lower with Ball Balance': 'إنزال الرجلين مع كرة توازن',
  'Stir the Pot Plank': 'بلانك تحريك القِدر',
  'Half Kneeling Vertical Pallof Press': 'بالوف برس عمودي بنصف ركوع',
  'Kneeling Vertical Pallof Press': 'بالوف برس عمودي راكعًا',
  'Standing Split Stance Vertical Pallof Press': 'بالوف برس عمودي بوقفة منفصلة',
  'Standing Athletic Stance Vertical Pallof Press': 'بالوف برس عمودي بوقفة رياضية',
  'Trx Fallout': 'فول أوت TRX',
  'Trx Straight Arm Plank': 'بلانك بذراعين مستقيمتين TRX',
  'Trunk Stability Push-Up': 'ضغط بثبات الجذع',
  'Stability Ball Roll Out': 'دحرجة على كرة التوازن',
  'Prone Plank with Single-Leg Hip Extension': 'بلانك مع مد الورك برجل واحدة',
  'Straight Arm Plank with Single-Leg Hip Extension': 'بلانك مستقيم الذراعين مع مد الورك برجل واحدة',
  'Prone Plank with Single-Leg Hip Abduction': 'بلانك مع إبعاد الورك برجل واحدة',
  'Straight Arm Plank with Single-Leg Hip Abduction': 'بلانك مستقيم الذراعين مع إبعاد الورك برجل واحدة',
  'Slide Board Body Saw': 'منشار الجسم على لوح الانزلاق',
  'Ab Wheel Rollout': 'دحرجة عجلة البطن',
  'Barbell Ab Rollout': 'دحرجة البار للبطن',
  'Dumbbell Ab Rollout': 'دحرجة الدمبل للبطن',
  'Army Crawl Plank': 'بلانك الزحف العسكري',
  'Mountain Climber': 'متسلق الجبل',
  'Plank Double Knee Tuck on Swiss ball': 'بلانك ضم الركبتين على كرة التوازن',
  'Plank Double Knee Tuck on Trx': 'بلانك ضم الركبتين على TRX',
  'Slide Board Knee Tuck': 'ضم الركبتين على لوح الانزلاق',
  'Slide Board Pike': 'بايك على لوح الانزلاق',
  'Bird Dog Exercise': 'تمرين بيرد دوج',
  'Dead Bug Exercise': 'تمرين ديد باغ',
  'Swiss Ball Pike': 'بايك على كرة التوازن',
  'Trx Pike': 'بايك TRX',
  'Mountain Climber on Stability Ball': 'متسلق الجبل على كرة التوازن',
  'Mountain Climber with Trx': 'متسلق الجبل مع TRX',
  'Slide Board Mountain Climber': 'متسلق الجبل على لوح الانزلاق',
  'Slide Board Simultaneous Abduction and Adduction': 'فتح وضم الرجلين معًا على لوح الانزلاق',
  'Slide Board Alternating Abduction and Adduction': 'فتح وضم الرجلين بالتناوب على لوح الانزلاق',
  'Layout Pike on Stability Ball': 'بايك ممدود على كرة التوازن',
  'Layout Pike on Trx': 'بايك ممدود على TRX',
  'Trx Body Saw': 'منشار الجسم TRX',
  'Trx Knee Tuck with Body Saw': 'ضم الركبتين مع منشار الجسم TRX',
  'Stability Ball Body Saw': 'منشار الجسم على كرة التوازن',
  'Elevated Oblique Crunches With Trx': 'كرنش جانبي مرتفع مع TRX',
  'Standing Horizontal Press with Resistance Band': 'ضغط أفقي واقفًا بحزام المقاومة',
  'Medicine Ball Rollout': 'دحرجة الكرة الطبية',
  'Standing Anti Rotation Pallof Press': 'بالوف برس مضاد للدوران واقفًا',
  'Supine Anti Rotation Pallof Press': 'بالوف برس مضاد للدوران مستلقيًا',
  'Half Kneeling Anti Rotation Pallof Press': 'بالوف برس مضاد للدوران بنصف ركوع',
  'Kneeling Anti Rotation Pallof Press': 'بالوف برس مضاد للدوران راكعًا',
  'One Arm Anti Rotation Suspension Row': 'تجديف معلق مضاد للدوران بذراع واحدة',
  'Anti Rotation Landmine Rainbow': 'قوس لاندماين مضاد للدوران',
  'Cable Standing Single Arm Horizontal Press': 'ضغط أفقي بذراع واحدة بالكيبل واقفًا',
  'Standing Single Arm Horizontal Press with Resistance Band': 'ضغط أفقي بذراع واحدة بحزام المقاومة',
  'Cable Standing Single Arm Horizontal Row': 'تجديف أفقي بذراع واحدة بالكيبل واقفًا',
  'Standing Single Arm Horizontal Row with Resistance Band': 'تجديف أفقي بذراع واحدة بحزام المقاومة',
  'Renegade Row': 'تجديف بلانك (رينيجيد)',
  'Push Ups Lock Off': 'ضغط بثبات ذراع واحدة (لوك أوف)',
  'Half Kneeling Anti Rotation Cable Chop': 'تقطيع كيبل مضاد للدوران بنصف ركوع',
  'Kneeling Anti Rotation Cable Chop': 'تقطيع كيبل مضاد للدوران راكعًا',
  'Standing Anti Rotation Cable Chop': 'تقطيع كيبل مضاد للدوران واقفًا',
  'Half Kneeling Cable Lift': 'رفعة كيبل قطرية بنصف ركوع',
  'Kneeling Cable Lift': 'رفعة كيبل قطرية راكعًا',
  'Standing Cable Lift': 'رفعة كيبل قطرية واقفًا',
  'Single Leg Romanian Deadlift': 'ديدلفت روماني برجل واحدة',
  'Cable Anti Rotation Reverse Lunge': 'لانج خلفي مضاد للدوران بالكيبل',
  'Anti Rotation Reverse Lunge with Resistance Band': 'لانج خلفي مضاد للدوران بحزام المقاومة',
  'Cable Anti Rotation Squat': 'سكوات مضاد للدوران بالكيبل',
  'Anti Rotation Squat with Resistance Band': 'سكوات مضاد للدوران بحزام المقاومة',
  'Plank Pull Through': 'بلانك مع سحب الوزن تحت الجسم',
  'Plank Bird Dog': 'بلانك بيرد دوج',
  'Dead Bug with Lateral Sled Pull': 'ديد باغ مع سحب الزلاجة جانبيًا',
  'Trx Anti Rotation Press': 'ضغط مضاد للدوران TRX',
  'Single Arm Dumbbell Row': 'تجديف بالدمبل بذراع واحدة',
  'Single Arm Dumbbell Chest Press': 'ضغط صدر بالدمبل بذراع واحدة',
  'Anti Rotation Push with Rip Trainer': 'دفع مضاد للدوران بجهاز ريب',
  'Anti Rotation Lunge with Rip Trainer': 'لانج مضاد للدوران بجهاز ريب',
  'One Arm Push-Up': 'ضغط بذراع واحدة',
  'Tapping Push-Up': 'ضغط مع لمس بالتناوب',
  'Lateral Sled High Pull': 'سحب عالٍ جانبي بالزلاجة',
  'Windshield Wipers Exercise': 'مساحات الزجاج',
  'Windshield Wipers with Medicine Ball Twister': 'مساحات الزجاج مع لف الكرة الطبية',
  'Thread the Needle Exercise': 'لضم الإبرة',
  'One Arm Standing Landmine Press': 'لاندماين برس بذراع واحدة واقفًا',
  'One Arm Kneeling Landmine Press': 'لاندماين برس بذراع واحدة راكعًا',
  'Side Plank with Cable Row': 'بلانك جانبي مع تجديف كيبل',
  'Straight Arm Plank with One-Arm Overhead': 'بلانك مستقيم الذراعين مع رفع ذراع فوق الرأس',
  'Bird Dog Crawl with Pull Through': 'زحف بيرد دوج مع سحب الوزن',
  'Lateral Sled Pull with Pallof Press': 'سحب الزلاجة جانبيًا مع بالوف برس',
  'Lateral Sled Pull with Pallof Press (Isometric Hold)': 'سحب الزلاجة جانبيًا مع بالوف برس (ثبات)',
  'Lateral Rolling Plank on Stability Ball': 'بلانك متدحرج جانبيًا على كرة التوازن',
  'Hip Roll on Stability Ball': 'تدوير الورك على كرة التوازن',
  'Hip Roll with Thread the Needle on Stability Ball': 'تدوير الورك مع لضم الإبرة على كرة التوازن',
  'Trx Hip Roll with Thread the Needle': 'تدوير الورك مع لضم الإبرة TRX',
  'Sandbag Around the World': 'حول العالم بكيس الرمل',
  'Side Elbow Plank': 'بلانك جانبي على الكوع',
  'Side Straight-Arm Plank': 'بلانك جانبي بذراع مستقيمة',
  'Side Elbow Plank with Leg Abduction': 'بلانك جانبي على الكوع مع رفع الرجل',
  'Lateral Pallof Press': 'بالوف برس جانبي',
  'Side Straight-Arm Plank with Leg Abduction': 'بلانك جانبي بذراع مستقيمة مع رفع الرجل',
  'Single-Arm Dumbbell Overhead Press': 'برس كتف بالدمبل بذراع واحدة',
  'Single-Arm Dumbbell Lunge': 'لانج بالدمبل بذراع واحدة',
  'Single-Arm Dumbbell Farmers Walk': 'مشية الفلاح بالدمبل بذراع واحدة',
  'Single-Arm Dumbbell Step-Up': 'صعود بالدمبل بذراع واحدة',
  'Kettlebell Suitcase Carry': 'حمل الحقيبة بالكيتل بل',
  'Side Plank on Stability Ball(Arms or Feet Elevated)': 'بلانك جانبي على كرة التوازن',
  'Side Elbow Plank with Knee Drive to Chest': 'بلانك جانبي على الكوع مع ضم الركبة للصدر',
  'Side Straight-Arm Plank with Knee Drive to Chest': 'بلانك جانبي بذراع مستقيمة مع ضم الركبة للصدر',
  'Side Elbow Plank on Proprioception Disk': 'بلانك جانبي على الكوع على قرص التوازن',
  'Side Straight-Arm Plank on Proprioception Disk': 'بلانك جانبي بذراع مستقيمة على قرص التوازن',
  'One Arm Kettlebell Racked Carry': 'حمل الكيتل بل على الصدر بذراع واحدة',
  'Bottoms-Up Kettlebell Walk': 'مشي بالكيتل بل مقلوبًا',
  'Dumbbell Suitcase Deadlift': 'ديدلفت الحقيبة بالدمبل',
  'Barbell Suitcase Deadlift': 'ديدلفت الحقيبة بالبار',
  'Kettlebell Suitcase Deadlift': 'ديدلفت الحقيبة بالكيتل بل',
  'Off-Bench Lateral Core Hold': 'ثبات جانبي خارج المقعد',
  'Offset Barbell Deadlift': 'ديدلفت بار غير متوازن',
  'Offset Barbell Squat': 'سكوات بار غير متوازن',
  'Offset Dumbbell Squat': 'سكوات دمبل غير متوازن',
  'Offset Barbell Press': 'برس بار غير متوازن',
  'Roman Chair Side Hold': 'ثبات جانبي على الكرسي الروماني',
  'Anti Lateral Flexion Landmine Rainbow': 'قوس لاندماين مضاد للانحناء الجانبي',
  'Elbow Reverse Plank': 'بلانك عكسي على الكوعين',
  'Straight Arm Reverse Plank': 'بلانك عكسي بذراعين مستقيمتين',
  'Single Leg Straight Arm Reverse Plank': 'بلانك عكسي برجل واحدة',
  'Straight Arm Reverse Plank with Leg Abduction': 'بلانك عكسي مع رفع الرجل جانبًا',
  'Bridge Hold': 'ثبات الجسر',
  'Single Leg Bridge Hold': 'ثبات الجسر برجل واحدة',
  'Hip Thrust Hold': 'ثبات هيب ثراست',
  'Single Leg Hip Thrust Hold': 'ثبات هيب ثراست برجل واحدة',
  'Roman Chair Hold': 'ثبات على الكرسي الروماني',
  'Reverse Hyper Hold': 'ثبات مد الظهر العكسي',
  'Trx Reverse Plank Pull Through': 'بلانك عكسي مع سحب TRX',
  'Trx Bridge Hold': 'ثبات الجسر TRX',
  'Trx Single Leg Bridge Hold': 'ثبات الجسر برجل واحدة TRX',
  'Stability Ball Bridge Hold': 'ثبات الجسر على كرة التوازن',
  'Stability Ball Single Leg Bridge Hold': 'ثبات الجسر برجل واحدة على كرة التوازن',
  'Front Rotary Medicine Ball Throw': 'رمي الكرة الطبية الدوراني للأمام',
  'Front Rotary Medicine Ball Press': 'ضغط الكرة الطبية الدوراني للأمام',
  'Side Rotary Medicine Ball Throw': 'رمي الكرة الطبية الدوراني جانبيًا',
  'Standing Reverse Half Rotation': 'نصف دوران عكسي واقفًا',
  'Standing Reverse Full Rotation': 'دوران عكسي كامل واقفًا',
  'High to Low Cable Wood Chop': 'تقطيع الحطّاب بالكيبل من أعلى لأسفل',
  'Low to High Cable Wood Chop': 'تقطيع الحطّاب بالكيبل من أسفل لأعلى',
  'Medicine Ball Rotary Punch Toss': 'رمي الكرة الطبية بلكمة دورانية',
  'Horizontal Cable Wood Chop': 'تقطيع الحطّاب بالكيبل أفقيًا',
  'Dumbbell Wood Chop': 'تقطيع الحطّاب بالدمبل',
  'Medicine Ball Wood Chop': 'تقطيع الحطّاب بالكرة الطبية',
  'Landmine Rotation': 'تدوير اللاندماين',
  'Battling Ropes Rainbow': 'قوس حبال التموج',
  'Medicine Ball Rotational Lunge': 'لانج دوراني بالكرة الطبية',
  'Sandbag Rotational Lunge': 'لانج دوراني بكيس الرمل',
  'Medicine Ball Crossover Step Throw': 'رمي الكرة الطبية مع خطوة متقاطعة',
  'Hanging Knee Circle': 'دوائر الركبتين معلقًا',
  'Hanging Leg Circle': 'دوائر الرجلين معلقًا',
  'Hanging Side Leg Raise': 'رفع الرجلين الجانبي معلقًا',
  'Hanging Bent Knees Windshield Wipers': 'مساحات الزجاج معلقًا بركبتين مثنيتين',
  'Hanging Extended Knees Windshield Wipers': 'مساحات الزجاج معلقًا بركبتين ممدودتين',
  'Floor Bent Knees Windshield Wipers': 'مساحات الزجاج أرضًا بركبتين مثنيتين',
  'Floor Extended Knees Windshield Wipers': 'مساحات الزجاج أرضًا بركبتين ممدودتين',
  'Medicine Ball Partner Rotation': 'تدوير الكرة الطبية مع شريك',
  'Medicine Ball Twisting Wall Toss': 'رمي الكرة الطبية على الحائط مع التواء',
  'Medicine Ball Rotational Slam': 'ضرب الكرة الطبية الدوراني',
  'Landmine Hang Clean to Rotational Press': 'لاندماين كلين مع برس دوراني',
  'Landmine Deadlift to Rotational Press': 'لاندماين ديدلفت مع برس دوراني',
  'Tornado Ball Twist': 'التواء كرة الإعصار',
  'Floor Prone Y Raise': 'رفعة Y منبطحًا أرضًا',
  'Stability Ball Prone Y Raise': 'رفعة Y منبطحًا على كرة التوازن',
  'Floor Prone Shoulder Horizontal Abduction': 'فتح الكتف الأفقي منبطحًا أرضًا',
  'Incline Bench Prone Shoulder Horizontal Abduction': 'فتح الكتف الأفقي منبطحًا على مقعد مائل',
  'Stability Ball Prone Shoulder Horizontal Abduction': 'فتح الكتف الأفقي منبطحًا على كرة التوازن',
  'Floor Prone Scapular Retraction and Depression': 'ضم وخفض لوحي الكتف منبطحًا أرضًا',
  'Incline Bench Prone Scapular Retraction and Depression': 'ضم وخفض لوحي الكتف على مقعد مائل',
  'Flat Bench Prone Scapular Retraction and Depression': 'ضم وخفض لوحي الكتف على مقعد مستوٍ',
  'Stability Ball Prone Scapular Retraction and Depression': 'ضم وخفض لوحي الكتف على كرة التوازن',
  'Resistance Band Pull Apart': 'فتح حزام المقاومة',
  'Standing Resistance Band Y Raise': 'رفعة Y بحزام المقاومة واقفًا',
  'Trx Prone Retraction and Protraction': 'ضم وإبعاد لوحي الكتف TRX',
  'Lower Traps Dip': 'متوازي الترابيس السفلية',
  'Floor Bridge': 'جسر أرضي',
  'Floor Bridge with Resistance Band': 'جسر أرضي بحزام المقاومة',
  'Floor Bridge with Medicine Ball': 'جسر أرضي بالكرة الطبية',
  'Single Leg Bridge': 'جسر برجل واحدة',
  'Bridge on Stability Ball': 'جسر على كرة التوازن',
  'Bridge with Resistance Band on Stability Ball': 'جسر بحزام المقاومة على كرة التوازن',
  'Bridge with Medicine Ball on Stability Ball': 'جسر بالكرة الطبية على كرة التوازن',
  'Single Leg Bridge on Stability Ball': 'جسر برجل واحدة على كرة التوازن',
  'Double Leg on Stability Ball Bridge': 'جسر والقدمان على كرة التوازن',
  'Single Leg on Stability Ball Bridge': 'جسر وقدم واحدة على كرة التوازن',
  'Single Leg Balance and Reach': 'توازن ومد برجل واحدة',
  'Bodyweight Hip Thrust': 'هيب ثراست بوزن الجسم',
  'Bodyweight Hip Thrust with Resistance Band': 'هيب ثراست بوزن الجسم بحزام المقاومة',
  'Single Leg Bodyweight Hip Thrust': 'هيب ثراست برجل واحدة بوزن الجسم',
  'Lateral Band Walk': 'مشي جانبي بحزام المقاومة',
  'Standing Unilateral Abduction with Resistance Band': 'إبعاد الرجل جانبيًا بحزام المقاومة واقفًا',
  'Clamshell Exercise': 'تمرين المحارة',
  'Clamshell Exercise with Resistance Band': 'تمرين المحارة بحزام المقاومة',
};

export const exNameAr = (name) => EXERCISE_NAMES_AR[name] || null;
