// GENERATED by scripts/build_exercise_bank.py — DO NOT EDIT BY HAND.
// Source: _archive/PTApp/program-source/2026-07-13-exercises-full-list.xlsx (Elie's bank).
// Regenerate + bump version only when Elie ships a new bank.
export const EXERCISE_BANK_VERSION = 1;

export const MUSCLE_GROUPS = {
  push: { major: 'Chest', minors: ['Shoulders', 'Triceps'] },
  pull: { major: 'Back', minors: ['Rear Delts', 'Biceps', 'Forearms'] },
  legs: { major: 'Legs', minors: ['Calves', 'Abs'] },
};

export const EXERCISES = [
  {
    "name": "Hammer Curl",
    "muscles": [
      "Biceps",
      "Forearms"
    ],
    "primary": "Biceps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Biceps",
    "advanced": false
  },
  {
    "name": "Shoulder External Rotation with Cable",
    "muscles": [
      "Rotator Cuffs"
    ],
    "primary": "Rotator Cuffs",
    "type": "isolation",
    "slot": null,
    "bucket": null,
    "advanced": false
  },
  {
    "name": "Seated Dumbbell Curl",
    "muscles": [
      "Biceps"
    ],
    "primary": "Biceps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Biceps",
    "advanced": false
  },
  {
    "name": "Dumbbell W Raise",
    "muscles": [
      "Rear Delts",
      "Rotator Cuffs"
    ],
    "primary": "Rear Delts",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Rear Delts",
    "advanced": false
  },
  {
    "name": "High Pulley Curl",
    "muscles": [
      "Biceps"
    ],
    "primary": "Biceps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Biceps",
    "advanced": false
  },
  {
    "name": "Barbell Curl",
    "muscles": [
      "Biceps"
    ],
    "primary": "Biceps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Biceps",
    "advanced": true
  },
  {
    "name": "Machine Curl",
    "muscles": [
      "Biceps"
    ],
    "primary": "Biceps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Biceps",
    "advanced": false
  },
  {
    "name": "Preacher Curl",
    "muscles": [
      "Biceps"
    ],
    "primary": "Biceps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Biceps",
    "advanced": false
  },
  {
    "name": "Reverse-Grip Barbell Curl",
    "muscles": [
      "Forearms",
      "Biceps"
    ],
    "primary": "Forearms",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Forearms",
    "advanced": true
  },
  {
    "name": "Barbell Reverse Wrist Curl",
    "muscles": [
      "Forearms"
    ],
    "primary": "Forearms",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Forearms",
    "advanced": true
  },
  {
    "name": "Barbell Wrist Curl",
    "muscles": [
      "Forearms"
    ],
    "primary": "Forearms",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Forearms",
    "advanced": true
  },
  {
    "name": "Triceps Pushdown",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "isolation",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "Reverse-Grip Cable Pushdown",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "isolation",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "One Arm Reverse-Grip Pushdown",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "isolation",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "Barbell Lying Triceps Extension",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "isolation",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": true
  },
  {
    "name": "Dumbbell Lying Triceps Extension",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "isolation",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "One Arm Overhead Dumbbell Triceps Extension",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "isolation",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "Seated Overhead Dumbbell Triceps Extension",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "isolation",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "Triceps Kickback",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "isolation",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "Triceps Dip",
    "muscles": [
      "Triceps"
    ],
    "primary": "Triceps",
    "type": "compound",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "Lying Shoulder External Rotation with Dumbbell",
    "muscles": [
      "Rotator Cuffs"
    ],
    "primary": "Rotator Cuffs",
    "type": "isolation",
    "slot": null,
    "bucket": null,
    "advanced": false
  },
  {
    "name": "Dumbbell Batwing",
    "muscles": [
      "Rotator Cuffs"
    ],
    "primary": "Rotator Cuffs",
    "type": "isolation",
    "slot": null,
    "bucket": null,
    "advanced": false
  },
  {
    "name": "Barbell Behind the Neck Press",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": true
  },
  {
    "name": "Seated Barbell Overhead Press",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": true
  },
  {
    "name": "Seated Dumbbell Overhead Press",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Arnold Dumbbell Press",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Bent-Over Lateral Raise",
    "muscles": [
      "Rear Delts",
      "Shoulders"
    ],
    "primary": "Rear Delts",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Rear Delts",
    "advanced": false
  },
  {
    "name": "Lateral Dumbbell Raise",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Front Dumbell Raise",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Side-Lying Lateral Raise",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Low-Pulley Lateral Raise",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Low-Pulley Front Raise",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "High-Pulley Lateral Extension",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Low-Pulley Bent-Over Lateral Raise",
    "muscles": [
      "Rear Delts",
      "Shoulders"
    ],
    "primary": "Rear Delts",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Rear Delts",
    "advanced": false
  },
  {
    "name": "Barbell Front Raise",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": true
  },
  {
    "name": "Upright Row",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Pec-Deck Rear Delt Raise",
    "muscles": [
      "Rear Delts",
      "Shoulders"
    ],
    "primary": "Rear Delts",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Rear Delts",
    "advanced": false
  },
  {
    "name": "Incline Barbell Press",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": true
  },
  {
    "name": "Flat Barbell Press",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": true
  },
  {
    "name": "Close Grip Bench Press",
    "muscles": [
      "Chest",
      "Triceps"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Wide Grip Bench Press",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Decline Barbell Press",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": true
  },
  {
    "name": "Push-Up",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Dip",
    "muscles": [
      "Chest",
      "Triceps"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Flat Dumbbell Press",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Flat Dumbbell Fly",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "isolation",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Incline Dumbbell Fly",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "isolation",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Pec-Deck Fly",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "isolation",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Cable Crossover Fly",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "isolation",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Dumbbell Pullover",
    "muscles": [
      "Chest",
      "Lats"
    ],
    "primary": "Chest",
    "type": "isolation",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Reverse Chin-Up",
    "muscles": [
      "Middle Back"
    ],
    "primary": "Middle Back",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Pull-Up",
    "muscles": [
      "Lats",
      "Middle Back"
    ],
    "primary": "Lats",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Wide Grip Lat Pull-Down",
    "muscles": [
      "Lats",
      "Middle Back"
    ],
    "primary": "Lats",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Close Grip Lat Pull-Down",
    "muscles": [
      "Lats",
      "Middle Back"
    ],
    "primary": "Lats",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Straight Arm Lat Pull-Down",
    "muscles": [
      "Lats"
    ],
    "primary": "Lats",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Seated Cable Row",
    "muscles": [
      "Lats",
      "Middle Back"
    ],
    "primary": "Lats",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "One Arm Dumbbell Row",
    "muscles": [
      "Lats",
      "Middle Back"
    ],
    "primary": "Lats",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Barbell Bent-Over Row",
    "muscles": [
      "Lats",
      "Middle Back",
      "Spinal Erectors"
    ],
    "primary": "Lats",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": true
  },
  {
    "name": "T-bar row",
    "muscles": [
      "Lats",
      "Middle Back"
    ],
    "primary": "Lats",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Cable Bent Over Row",
    "muscles": [
      "Lats",
      "Middle Back"
    ],
    "primary": "Lats",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Deadlift",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Spinal Erectors",
      "Lats"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Back Extension",
    "muscles": [
      "Spinal Erectors"
    ],
    "primary": "Spinal Erectors",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Machine Torso Extension",
    "muscles": [
      "Spinal Erectors"
    ],
    "primary": "Spinal Erectors",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Barbell Shrug",
    "muscles": [
      "Traps"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": true
  },
  {
    "name": "Dumbbell Shrug",
    "muscles": [
      "Traps"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Dumbbell Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Front Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Back Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Leg Press",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Hack Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Barbell Split Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Plyometric Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Ball Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Bodyweight Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Sumo Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Smith Machine Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Leg Extension",
    "muscles": [
      "Quads"
    ],
    "primary": "Quads",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Lying Leg Curl",
    "muscles": [
      "Hamstrings"
    ],
    "primary": "Hamstrings",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Standing Leg Curl",
    "muscles": [
      "Hamstrings"
    ],
    "primary": "Hamstrings",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Seated Leg Curl",
    "muscles": [
      "Hamstrings"
    ],
    "primary": "Hamstrings",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Good Morning",
    "muscles": [
      "Hamstrings",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Hamstrings",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Bulgarian Split Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Dumbbell Lunge",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Barbell Lunge",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Walking Lunge",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Plyometric Lunge",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Stiff-Legged Deadlift",
    "muscles": [
      "Hamstrings",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Hamstrings",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Sumo Deadlift",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Cable Adduction",
    "muscles": [
      "Adductors"
    ],
    "primary": "Adductors",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Adduction Machine",
    "muscles": [
      "Adductors"
    ],
    "primary": "Adductors",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Abduction Machine",
    "muscles": [
      "Abductors"
    ],
    "primary": "Abductors",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Standing Calf Raise",
    "muscles": [
      "Calves"
    ],
    "primary": "Calves",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Calves",
    "advanced": false
  },
  {
    "name": "Dumbbell Standing Calf Raise",
    "muscles": [
      "Calves"
    ],
    "primary": "Calves",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Calves",
    "advanced": false
  },
  {
    "name": "One Leg Toe Raise",
    "muscles": [
      "Calves"
    ],
    "primary": "Calves",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Calves",
    "advanced": false
  },
  {
    "name": "Donkey Calf Raise",
    "muscles": [
      "Calves"
    ],
    "primary": "Calves",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Calves",
    "advanced": false
  },
  {
    "name": "Seated Calf Raise",
    "muscles": [
      "Calves"
    ],
    "primary": "Calves",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Calves",
    "advanced": false
  },
  {
    "name": "Bodyweight Back Kick",
    "muscles": [
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Machine Hip Extension",
    "muscles": [
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Cable Back Kick",
    "muscles": [
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Floor Valslide Leg Curl",
    "muscles": [
      "Hamstrings"
    ],
    "primary": "Hamstrings",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Cable Hip Abduction",
    "muscles": [
      "Abductors"
    ],
    "primary": "Abductors",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Standing Machine Hip Abduction",
    "muscles": [
      "Abductors"
    ],
    "primary": "Abductors",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Floor Hip Abduction",
    "muscles": [
      "Abductors"
    ],
    "primary": "Abductors",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Nordic Hamstring Curl",
    "muscles": [
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Floor Sit-up",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Incline Bench Sit-up",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "High-Pulley Crunch",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Ab Crunch Machine",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Leg Raise",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Hanging Leg Raise",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Broomstick Twist",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Dumbbell Side Bend",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Obliques Roman Chair Side Bend",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Machine Trunk Rotation",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Russian Twist",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Chest Press Machine",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Chest Stretch",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "isolation",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Cable Biceps Curl",
    "muscles": [
      "Biceps"
    ],
    "primary": "Biceps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Biceps",
    "advanced": false
  },
  {
    "name": "Dumbbell Row",
    "muscles": [
      "Shoulders",
      "Upper Back"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Oblique Crunch",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Dumbbell Deadlift",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Spinal Erectors",
      "Lats"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Dumbbell Romanian Deadlift",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Dumbbell Sumo Squat",
    "muscles": [
      "Quads"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Dumbbell Bridge",
    "muscles": [
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Single Leg Squat",
    "muscles": [
      "Quads"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "One Arm Dumbbell Front Raise",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "One Arm Dumbbell Lateral Raise",
    "muscles": [
      "Shoulders"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Leg Press Wide Stance",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Quads",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Barbell Hip Thruster",
    "muscles": [
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Crunches",
    "muscles": [
      "Abs"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "TRX Chest",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "isolation",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Halting Deadlift",
    "muscles": [
      "Quads"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Rack Pull",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Power Shrug",
    "muscles": [
      "Traps"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Deficit Deadlift",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Glute Ham Raise",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Reverse Hyperextension",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Box Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Power Rack Partial Squat",
    "muscles": [
      "Quads",
      "Hamstrings",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Power Rack Partial Bench Press",
    "muscles": [
      "Chest"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": true
  },
  {
    "name": "Push Press",
    "muscles": [
      "Shoulders",
      "Traps"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": true
  },
  {
    "name": "Power Rack Partial Shoulder Press",
    "muscles": [
      "Shoulders",
      "Traps"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": true
  },
  {
    "name": "Prone Plank",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Straight Arm Plank",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Prone Plank on Stability Ball (Arms or Feet Elevated)",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Straight Arm Plank on Stability Ball(Arms or Feet Elevated)",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Bent Knees Leg Lower",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Extended Knees Leg Lower",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Leg Lower with Ball Balance",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Stir the Pot Plank",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Half Kneeling Vertical Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Kneeling Vertical Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Standing Split Stance Vertical Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Standing Athletic Stance Vertical Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Fallout",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Straight Arm Plank",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trunk Stability Push-Up",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Stability Ball Roll Out",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Prone Plank with Single-Leg Hip Extension",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Straight Arm Plank with Single-Leg Hip Extension",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes",
      "Hamstrings"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Prone Plank with Single-Leg Hip Abduction",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Straight Arm Plank with Single-Leg Hip Abduction",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Slide Board Body Saw",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Ab Wheel Rollout",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Barbell Ab Rollout",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": true
  },
  {
    "name": "Dumbbell Ab Rollout",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Army Crawl Plank",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Mountain Climber",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Plank Double Knee Tuck on Swiss ball",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Plank Double Knee Tuck on Trx",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Slide Board Knee Tuck",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Slide Board Pike",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Bird Dog Exercise",
    "muscles": [
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Dead Bug Exercise",
    "muscles": [
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Swiss Ball Pike",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Pike",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Mountain Climber on Stability Ball",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Mountain Climber with Trx",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Slide Board Mountain Climber",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Slide Board Simultaneous Abduction and Adduction",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes",
      "Adductors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Slide Board Alternating Abduction and Adduction",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes",
      "Adductors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Layout Pike on Stability Ball",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Layout Pike on Trx",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Body Saw",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Knee Tuck with Body Saw",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Stability Ball Body Saw",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Elevated Oblique Crunches With Trx",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Standing Horizontal Press with Resistance Band",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Medicine Ball Rollout",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Standing Anti Rotation Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Supine Anti Rotation Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Half Kneeling Anti Rotation Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Kneeling Anti Rotation Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "One Arm Anti Rotation Suspension Row",
    "muscles": [
      "Back",
      "Abs",
      "Obliques"
    ],
    "primary": "Back",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Anti Rotation Landmine Rainbow",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Cable Standing Single Arm Horizontal Press",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Standing Single Arm Horizontal Press with Resistance Band",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Cable Standing Single Arm Horizontal Row",
    "muscles": [
      "Back",
      "Abs",
      "Obliques"
    ],
    "primary": "Back",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Standing Single Arm Horizontal Row with Resistance Band",
    "muscles": [
      "Back",
      "Abs",
      "Obliques"
    ],
    "primary": "Back",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Renegade Row",
    "muscles": [
      "Back",
      "Abs",
      "Obliques"
    ],
    "primary": "Back",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Push Ups Lock Off",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Half Kneeling Anti Rotation Cable Chop",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Kneeling Anti Rotation Cable Chop",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Standing Anti Rotation Cable Chop",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Half Kneeling Cable Lift",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Kneeling Cable Lift",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Standing Cable Lift",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Single Leg Romanian Deadlift",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Cable Anti Rotation Reverse Lunge",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Quads",
      "Abs",
      "Obliques"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Anti Rotation Reverse Lunge with Resistance Band",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Quads",
      "Abs",
      "Obliques"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Cable Anti Rotation Squat",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Quads",
      "Abs",
      "Obliques"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Anti Rotation Squat with Resistance Band",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Quads",
      "Abs",
      "Obliques"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Plank Pull Through",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Plank Bird Dog",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Dead Bug with Lateral Sled Pull",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Anti Rotation Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Single Arm Dumbbell Row",
    "muscles": [
      "Back",
      "Abs",
      "Obliques"
    ],
    "primary": "Back",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Single Arm Dumbbell Chest Press",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Anti Rotation Push with Rip Trainer",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Anti Rotation Lunge with Rip Trainer",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Quads",
      "Abs",
      "Obliques"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "One Arm Push-Up",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Tapping Push-Up",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Lateral Sled High Pull",
    "muscles": [
      "Shoulders",
      "Abs",
      "Obliques"
    ],
    "primary": "Shoulders",
    "type": "isolation",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Windshield Wipers Exercise",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Windshield Wipers with Medicine Ball Twister",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Thread the Needle Exercise",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "One Arm Standing Landmine Press",
    "muscles": [
      "Shoulders",
      "Abs",
      "Obliques"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "One Arm Kneeling Landmine Press",
    "muscles": [
      "Shoulders",
      "Abs",
      "Obliques"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Side Plank with Cable Row",
    "muscles": [
      "Back",
      "Abs",
      "Obliques"
    ],
    "primary": "Back",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Straight Arm Plank with One-Arm Overhead",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Bird Dog Crawl with Pull Through",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Lateral Sled Pull with Pallof Press",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Lateral Sled Pull with Pallof Press (Isometric Hold)",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Lateral Rolling Plank on Stability Ball",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Hip Roll on Stability Ball",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Hip Roll with Thread the Needle on Stability Ball",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Hip Roll with Thread the Needle",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Sandbag Around the World",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Side Elbow Plank",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Side Straight-Arm Plank",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Side Elbow Plank with Leg Abduction",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Lateral Pallof Press",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Side Straight-Arm Plank with Leg Abduction",
    "muscles": [
      "Abs",
      "Obliques",
      "Glutes"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Single-Arm Dumbbell Overhead Press",
    "muscles": [
      "Shoulders",
      "Abs",
      "Obliques"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Single-Arm Dumbbell Lunge",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Single-Arm Dumbbell Farmers Walk",
    "muscles": [
      "Forearms",
      "Abs",
      "Obliques"
    ],
    "primary": "Forearms",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Forearms",
    "advanced": false
  },
  {
    "name": "Single-Arm Dumbbell Step-Up",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Kettlebell Suitcase Carry",
    "muscles": [
      "Forearms",
      "Abs",
      "Obliques"
    ],
    "primary": "Forearms",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Forearms",
    "advanced": false
  },
  {
    "name": "Side Plank on Stability Ball(Arms or Feet Elevated)",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Side Elbow Plank with Knee Drive to Chest",
    "muscles": [
      "Psoas",
      "Abs",
      "Obliques"
    ],
    "primary": "Psoas",
    "type": "isolation",
    "slot": null,
    "bucket": null,
    "advanced": false
  },
  {
    "name": "Side Straight-Arm Plank with Knee Drive to Chest",
    "muscles": [
      "Psoas",
      "Abs",
      "Obliques"
    ],
    "primary": "Psoas",
    "type": "isolation",
    "slot": null,
    "bucket": null,
    "advanced": false
  },
  {
    "name": "Side Elbow Plank on Proprioception Disk",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Side Straight-Arm Plank on Proprioception Disk",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "One Arm Kettlebell Racked Carry",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Bottoms-Up Kettlebell Walk",
    "muscles": [
      "Forearms",
      "Abs",
      "Obliques"
    ],
    "primary": "Forearms",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Forearms",
    "advanced": false
  },
  {
    "name": "Dumbbell Suitcase Deadlift",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Barbell Suitcase Deadlift",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Kettlebell Suitcase Deadlift",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Off-Bench Lateral Core Hold",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Offset Barbell Deadlift",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Offset Barbell Squat",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": true
  },
  {
    "name": "Offset Dumbbell Squat",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Offset Barbell Press",
    "muscles": [
      "Shoulders",
      "Abs",
      "Obliques"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": true
  },
  {
    "name": "Roman Chair Side Hold",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Anti Lateral Flexion Landmine Rainbow",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Elbow Reverse Plank",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Straight Arm Reverse Plank",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Single Leg Straight Arm Reverse Plank",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Straight Arm Reverse Plank with Leg Abduction",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Bridge Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Single Leg Bridge Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Hip Thrust Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "compound",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Single Leg Hip Thrust Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "compound",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Roman Chair Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Reverse Hyper Hold",
    "muscles": [
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Trx Reverse Plank Pull Through",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Bridge Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Trx Single Leg Bridge Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Stability Ball Bridge Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Stability Ball Single Leg Bridge Hold",
    "muscles": [
      "Abs",
      "Glutes",
      "Spinal Erectors"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Front Rotary Medicine Ball Throw",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "compound",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Front Rotary Medicine Ball Press",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "compound",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Side Rotary Medicine Ball Throw",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "compound",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Standing Reverse Half Rotation",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Standing Reverse Full Rotation",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "High to Low Cable Wood Chop",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Low to High Cable Wood Chop",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Medicine Ball Rotary Punch Toss",
    "muscles": [
      "Chest",
      "Abs",
      "Obliques"
    ],
    "primary": "Chest",
    "type": "isolation",
    "slot": "push",
    "bucket": "Chest",
    "advanced": false
  },
  {
    "name": "Horizontal Cable Wood Chop",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Dumbbell Wood Chop",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Medicine Ball Wood Chop",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Landmine Rotation",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Battling Ropes Rainbow",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Medicine Ball Rotational Lunge",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Sandbag Rotational Lunge",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Medicine Ball Crossover Step Throw",
    "muscles": [
      "Triceps",
      "Abs",
      "Obliques"
    ],
    "primary": "Triceps",
    "type": "compound",
    "slot": "push",
    "bucket": "Triceps",
    "advanced": false
  },
  {
    "name": "Hanging Knee Circle",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Hanging Leg Circle",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Hanging Side Leg Raise",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Hanging Bent Knees Windshield Wipers",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Hanging Extended Knees Windshield Wipers",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Floor Bent Knees Windshield Wipers",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Floor Extended Knees Windshield Wipers",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Medicine Ball Partner Rotation",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Medicine Ball Twisting Wall Toss",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Medicine Ball Rotational Slam",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Landmine Hang Clean to Rotational Press",
    "muscles": [
      "Shoulders",
      "Abs",
      "Obliques"
    ],
    "primary": "Shoulders",
    "type": "compound",
    "slot": "push",
    "bucket": "Shoulders",
    "advanced": false
  },
  {
    "name": "Landmine Deadlift to Rotational Press",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Abs",
      "Obliques",
      "Shoulders"
    ],
    "primary": "Quads",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Tornado Ball Twist",
    "muscles": [
      "Abs",
      "Obliques"
    ],
    "primary": "Abs",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Abs",
    "advanced": false
  },
  {
    "name": "Floor Prone Y Raise",
    "muscles": [
      "Traps",
      "Spinal Erectors"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Stability Ball Prone Y Raise",
    "muscles": [
      "Traps",
      "Spinal Erectors"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Floor Prone Shoulder Horizontal Abduction",
    "muscles": [
      "Traps",
      "Spinal Erectors",
      "Shoulders"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Incline Bench Prone Shoulder Horizontal Abduction",
    "muscles": [
      "Traps",
      "Spinal Erectors",
      "Shoulders"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Stability Ball Prone Shoulder Horizontal Abduction",
    "muscles": [
      "Traps",
      "Spinal Erectors",
      "Shoulders"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Floor Prone Scapular Retraction and Depression",
    "muscles": [
      "Traps",
      "Spinal Erectors"
    ],
    "primary": "Traps",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Incline Bench Prone Scapular Retraction and Depression",
    "muscles": [
      "Traps",
      "Spinal Erectors"
    ],
    "primary": "Traps",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Flat Bench Prone Scapular Retraction and Depression",
    "muscles": [
      "Traps",
      "Spinal Erectors"
    ],
    "primary": "Traps",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Stability Ball Prone Scapular Retraction and Depression",
    "muscles": [
      "Traps",
      "Spinal Erectors"
    ],
    "primary": "Traps",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Resistance Band Pull Apart",
    "muscles": [
      "Traps",
      "Spinal Erectors",
      "Shoulders"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Standing Resistance Band Y Raise",
    "muscles": [
      "Traps",
      "Spinal Erectors"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Trx Prone Retraction and Protraction",
    "muscles": [
      "Traps",
      "Serratus"
    ],
    "primary": "Traps",
    "type": "isolation",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Lower Traps Dip",
    "muscles": [
      "Traps"
    ],
    "primary": "Traps",
    "type": "compound",
    "slot": "pull",
    "bucket": "Back",
    "advanced": false
  },
  {
    "name": "Floor Bridge",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Floor Bridge with Resistance Band",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Floor Bridge with Medicine Ball",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors",
      "Adductors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Single Leg Bridge",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Bridge on Stability Ball",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Bridge with Resistance Band on Stability Ball",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Bridge with Medicine Ball on Stability Ball",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Single Leg Bridge on Stability Ball",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Double Leg on Stability Ball Bridge",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Single Leg on Stability Ball Bridge",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Single Leg Balance and Reach",
    "muscles": [
      "Quads",
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Quads",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Bodyweight Hip Thrust",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Bodyweight Hip Thrust with Resistance Band",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Single Leg Bodyweight Hip Thrust",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "compound",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Lateral Band Walk",
    "muscles": [
      "Glutes",
      "Hamstrings",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Standing Unilateral Abduction with Resistance Band",
    "muscles": [
      "Glutes",
      "Abs",
      "Obliques",
      "Spinal Erectors"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Clamshell Exercise",
    "muscles": [
      "Glutes"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  },
  {
    "name": "Clamshell Exercise with Resistance Band",
    "muscles": [
      "Glutes"
    ],
    "primary": "Glutes",
    "type": "isolation",
    "slot": "legs",
    "bucket": "Legs",
    "advanced": false
  }
];

// All exercises whose primary muscle rolls up into `bucket` (major or minor name).
export const bankForBucket = (bucket) => EXERCISES.filter(e => e.bucket === bucket);
